<?xml version="1.0" encoding="utf-8"?><Database Name="DiemDanh" Class="dbDiemDanhDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-0EHBBHL\SQLEXPRESS;Initial Catalog=DiemDanh;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DiemDanhConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CHITIETDANGNHAP" Member="CHITIETDANGNHAPs">
    <Type Name="CHITIETDANGNHAP">
      <Column Name="IDPHANQUYEN" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDDANGNHAP" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="THOIGIANDANGNHAP" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="CHITIETDANGNHAP_SINHVIEN" Member="SINHVIENs" ThisKey="IDPHANQUYEN,IDDANGNHAP" OtherKey="IDPHANQUYEN,IDDANGNHAP" Type="SINHVIEN" />
      <Association Name="CHITIETDANGNHAP_GIANGVIEN" Member="GIANGVIENs" ThisKey="IDPHANQUYEN,IDDANGNHAP" OtherKey="IDPHANQUYEN,IDDANGNHAP" Type="GIANGVIEN" />
      <Association Name="CHITIETDANGNHAP_QUANTRIVIEN" Member="QUANTRIVIENs" ThisKey="IDPHANQUYEN,IDDANGNHAP" OtherKey="IDPHANQUYEN,IDDANGNHAP" Type="QUANTRIVIEN" />
      <Association Name="DANGNHAP_CHITIETDANGNHAP" Member="DANGNHAP" ThisKey="IDDANGNHAP" OtherKey="IDDANGNHAP" Type="DANGNHAP" IsForeignKey="true" />
      <Association Name="PHANQUYEN_CHITIETDANGNHAP" Member="PHANQUYEN" ThisKey="IDPHANQUYEN" OtherKey="IDPHANQUYEN" Type="PHANQUYEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SINHVIEN" Member="SINHVIENs">
    <Type Name="SINHVIEN">
      <Column Name="IDSINHVIEN" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MASOSINHVIEN" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="TENSINHVIEN" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="NGAYSINH" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="SODIENTHOAI" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(1)" CanBeNull="true" />
      <Column Name="IDLOPSINHVIEN" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDPHANQUYEN" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDDANGNHAP" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="SINHVIEN_DANHSACHLOP" Member="DANHSACHLOPs" ThisKey="IDSINHVIEN" OtherKey="IDSINHVIEN" Type="DANHSACHLOP" />
      <Association Name="CHITIETDANGNHAP_SINHVIEN" Member="CHITIETDANGNHAP" ThisKey="IDPHANQUYEN,IDDANGNHAP" OtherKey="IDPHANQUYEN,IDDANGNHAP" Type="CHITIETDANGNHAP" IsForeignKey="true" />
      <Association Name="LOPSINHVIEN_SINHVIEN" Member="LOPSINHVIEN" ThisKey="IDLOPSINHVIEN" OtherKey="IDLOPSINHVIEN" Type="LOPSINHVIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DANGNHAP" Member="DANGNHAPs">
    <Type Name="DANGNHAP">
      <Column Name="IDDANGNHAP" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IDPHANQUYEN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TENDANGNHAP" Type="System.String" DbType="Char(50)" CanBeNull="true" />
      <Column Name="MATKHAU" Type="System.String" DbType="Char(50)" CanBeNull="true" />
      <Association Name="DANGNHAP_CHITIETDANGNHAP" Member="CHITIETDANGNHAPs" ThisKey="IDDANGNHAP" OtherKey="IDDANGNHAP" Type="CHITIETDANGNHAP" />
    </Type>
  </Table>
  <Table Name="dbo.DANHSACHLOP" Member="DANHSACHLOPs">
    <Type Name="DANHSACHLOP">
      <Column Name="IDLOPMH" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDSINHVIEN" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="DANHSACHLOP_LICHHOC" Member="LICHHOCs" ThisKey="IDLOPMH,IDSINHVIEN" OtherKey="IDLOPMH,IDSINHVIEN" Type="LICHHOC" />
      <Association Name="SINHVIEN_DANHSACHLOP" Member="SINHVIEN" ThisKey="IDSINHVIEN" OtherKey="IDSINHVIEN" Type="SINHVIEN" IsForeignKey="true" />
      <Association Name="LOPMONHOC_DANHSACHLOP" Member="LOPMONHOC" ThisKey="IDLOPMH" OtherKey="IDLOPMH" Type="LOPMONHOC" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DIEMDANHSV" Member="DIEMDANHSVs">
    <Type Name="DIEMDANHSV">
      <Column Name="IDDDSV" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="THOIGIANDDSV" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="GHICHU" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="IDLICHHOC" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDLOPMH" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDSINHVIEN" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="LICHHOC_DIEMDANHSV" Member="LICHHOC" ThisKey="IDLICHHOC,IDLOPMH,IDSINHVIEN" OtherKey="IDLICHHOC,IDLOPMH,IDSINHVIEN" Type="LICHHOC" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.GIANGVIEN" Member="GIANGVIENs">
    <Type Name="GIANGVIEN">
      <Column Name="IDGIANGVIEN" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MAGIANGVIEN" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="TENGIANGVIEN" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="NGAYSINH" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(1)" CanBeNull="true" />
      <Column Name="SODIENTHOAI" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="IDPHANQUYEN" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDDANGNHAP" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="GIANGVIEN_LOPMONHOC" Member="LOPMONHOCs" ThisKey="IDGIANGVIEN" OtherKey="IDGIANGVIEN" Type="LOPMONHOC" />
      <Association Name="CHITIETDANGNHAP_GIANGVIEN" Member="CHITIETDANGNHAP" ThisKey="IDPHANQUYEN,IDDANGNHAP" OtherKey="IDPHANQUYEN,IDDANGNHAP" Type="CHITIETDANGNHAP" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HOCKY" Member="HOCKies">
    <Type Name="HOCKY">
      <Column Name="IDHOCKY" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MAHOCKY" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="TENHOCKY" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="IDNAMHOC" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="HOCKY_LOPMONHOC" Member="LOPMONHOCs" ThisKey="IDHOCKY" OtherKey="IDHOCKY" Type="LOPMONHOC" />
      <Association Name="NAMHOC_HOCKY" Member="NAMHOC" ThisKey="IDNAMHOC" OtherKey="IDNAMHOC" Type="NAMHOC" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LICHHOC" Member="LICHHOCs">
    <Type Name="LICHHOC">
      <Column Name="IDLICHHOC" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="THOIGIANDIEMDANH" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="TUANHOC" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MAQR" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="IDLOPMH" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDSINHVIEN" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="LICHHOC_DIEMDANHSV" Member="DIEMDANHSVs" ThisKey="IDLICHHOC,IDLOPMH,IDSINHVIEN" OtherKey="IDLICHHOC,IDLOPMH,IDSINHVIEN" Type="DIEMDANHSV" />
      <Association Name="DANHSACHLOP_LICHHOC" Member="DANHSACHLOP" ThisKey="IDLOPMH,IDSINHVIEN" OtherKey="IDLOPMH,IDSINHVIEN" Type="DANHSACHLOP" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LOPMONHOC" Member="LOPMONHOCs">
    <Type Name="LOPMONHOC">
      <Column Name="IDLOPMH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MALOPMH" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="TENLOPMH" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="NHOMMONHOC" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TOTHUCHANH" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="THU" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="SOTIET" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TIETBATDAU" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NGAYBATDAU" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="NGAYKETTHUC" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="PHONGHOC" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="IDGIANGVIEN" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDMONHOC" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDHOCKY" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="LOPMONHOC_DANHSACHLOP" Member="DANHSACHLOPs" ThisKey="IDLOPMH" OtherKey="IDLOPMH" Type="DANHSACHLOP" />
      <Association Name="GIANGVIEN_LOPMONHOC" Member="GIANGVIEN" ThisKey="IDGIANGVIEN" OtherKey="IDGIANGVIEN" Type="GIANGVIEN" IsForeignKey="true" />
      <Association Name="HOCKY_LOPMONHOC" Member="HOCKY" ThisKey="IDHOCKY" OtherKey="IDHOCKY" Type="HOCKY" IsForeignKey="true" />
      <Association Name="MONHOC_LOPMONHOC" Member="MONHOC" ThisKey="IDMONHOC" OtherKey="IDMONHOC" Type="MONHOC" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LOPSINHVIEN" Member="LOPSINHVIENs">
    <Type Name="LOPSINHVIEN">
      <Column Name="IDLOPSINHVIEN" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MALOPSV" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="TENLOPSV" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="LOPSINHVIEN_SINHVIEN" Member="SINHVIENs" ThisKey="IDLOPSINHVIEN" OtherKey="IDLOPSINHVIEN" Type="SINHVIEN" />
    </Type>
  </Table>
  <Table Name="dbo.MONHOC" Member="MONHOCs">
    <Type Name="MONHOC">
      <Column Name="IDMONHOC" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MAMONHOC" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="TENMONHOC" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="SOBUOI" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SOTINCHI" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="MONHOC_LOPMONHOC" Member="LOPMONHOCs" ThisKey="IDMONHOC" OtherKey="IDMONHOC" Type="LOPMONHOC" />
    </Type>
  </Table>
  <Table Name="dbo.NAMHOC" Member="NAMHOCs">
    <Type Name="NAMHOC">
      <Column Name="IDNAMHOC" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MANAMHOC" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="TENNAMHOC" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="NAMHOC_HOCKY" Member="HOCKies" ThisKey="IDNAMHOC" OtherKey="IDNAMHOC" Type="HOCKY" />
    </Type>
  </Table>
  <Table Name="dbo.PHANQUYEN" Member="PHANQUYENs">
    <Type Name="PHANQUYEN">
      <Column Name="IDPHANQUYEN" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TENQUYEN" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="PHANQUYEN_CHITIETDANGNHAP" Member="CHITIETDANGNHAPs" ThisKey="IDPHANQUYEN" OtherKey="IDPHANQUYEN" Type="CHITIETDANGNHAP" />
    </Type>
  </Table>
  <Table Name="dbo.QUANTRIVIEN" Member="QUANTRIVIENs">
    <Type Name="QUANTRIVIEN">
      <Column Name="IDQTV" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MAQTV" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="TENQTV" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="TRANGTHAI" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PHANQUYENQTV" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IDPHANQUYEN" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDDANGNHAP" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="CHITIETDANGNHAP_QUANTRIVIEN" Member="CHITIETDANGNHAP" ThisKey="IDPHANQUYEN,IDDANGNHAP" OtherKey="IDPHANQUYEN,IDDANGNHAP" Type="CHITIETDANGNHAP" IsForeignKey="true" />
    </Type>
  </Table>
</Database>